In [1]:
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [2]:
90 + 89

179

### Variables

In [3]:
# Store the value 9 in variable num1
num1 = 9

In [6]:
# What is the value of variable num1
num1  # print(num1) will also print the same output

9

In [10]:
# Multiply variable num1 by another number(8)
num1 * 8

72

In [11]:
# Add a number to variable num1
num1 + 26

35

In [12]:
# Change the value of variable num1
num1 = 24

In [13]:
# Multiply variable num1 by another number(60)
num1 * 60

1440

In [14]:
# Add a number to variable num1
num1 + 33

57

In [ ]:
# Store/assign the value of 67 in variable num2
num2 = 67

In [16]:
# Add variables num1 and num2
num1 + num2

91

In [18]:
# Create variable town and assign it to Rustenburg
town = 'Rustenburg'

In [19]:
town

'Rustenburg'

### Exercise 1

Three new variables: hourly_minimum_wage, hours_per_week and week_per_year equals to 15, 40 and 52 respectively

1. Determine the number of working hours in a year, store it in a variable and output that
2. Determine the minimum earning per year
3. Determine the minimum earning per year using the original variables that were defined

In [20]:
# Variables
hourly_minimum_wage = 15
hours_per_week = 40
week_per_year = 52

In [21]:
# Number of working hours in a year
working_hours_per_year = hours_per_week * week_per_year
working_hours_per_year

2080

In [22]:
# minimum earning per year
working_hours_per_year * hourly_minimum_wage

31200

In [23]:
# minimum earning per year using the original variables that were defined
hourly_minimum_wage * hours_per_week * week_per_year

31200

## Arrays

In [24]:
# np.array is used to create an array
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [25]:
# Equate the above array to A
A = np.array([1,2,3,4,5,6])

In [26]:
A

array([1, 2, 3, 4, 5, 6])

In [27]:
# Multiply A by a number
A * 4

array([ 4,  8, 12, 16, 20, 24])

In [28]:
# Add a number to A 
A + 5

array([ 6,  7,  8,  9, 10, 11])

In [30]:
# Add the elements of array 
sum(A)

np.int64(21)

### Exercise 2

Create a new array with elements 11, 13, 15 and 17 and store it in Variable B. array A elements are 1, 2, 3, 4

1. Add A and B
2. Create a new variable a and equate that to number
3. Add a and B
4. Create 2 variables a and b and equate that to 9 and 5; then create array with the first element a+b and second element a*b
5. Create a new array with elements 4, 5, and 7; and store it in variable C
6. Display A
7. Print A
8. Add A and C 



In [35]:
A = np.array([1, 2, 3, 4])
B = np.array([11, 13, 15, 17])

In [38]:
# add A and B
A + B

array([12, 15, 18, 21])

In [39]:
# variable a
a = 6

In [40]:
# Add a and B
a + B

array([17, 19, 21, 23])

In [43]:
# array with the first element a+b and second element a*b(a=9 and b=5)
a = 9
b = 5

np.array([a+b, a*b])

array([14, 45])

In [44]:
# array with elements 4, 5, and 7; store it in Variable C
C = np.array([4, 5, 7])

In [45]:
# Display A
A = np.array([1, 2, 3, 4])

In [46]:
# Print A
A

array([1, 2, 3, 4])

In [49]:
# Add A and C
C_padded = np.pad(C, (0, 1), mode = 'constant')
result = C_padded + A
result

array([ 5,  7, 10,  4])

## Basic Array

np.arange() function uses the following basic syntax


np.arange(start,stop,step)

where:

* start: the starting value of the sequence 
* stop: the end value of the sequence
* step: the spacing between values


In [50]:
# Write an np.arange command with one input. Let that be 7
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [51]:
# What if i want the array to start at 1 and end in the value of input
np.arange(7) + 1

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# other way
np.arange(1,8)

array([1, 2, 3, 4, 5, 6, 7])

In [53]:
# create array that starts with 200 and ends 211
np.arange(200,212)

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211])

In [54]:
# np.arange with two input separated by comma
np.arange(1,8,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5])

### np.linspace

the np.linspace() function uses the following basic syntax
np.linspace(start, stop, num, ...)

where:

* start: the starting value of the sequence
* stop: the end value of the sequence
* num: the number of values to generate

In [55]:
# create sequence of 11 evenly spaced values between 0 and 20
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [58]:
a = np.linspace(0,10,3)
print(a)

[ 0.  5. 10.]


In [59]:
print(a.dtype)

float64


In [ ]:
# change the dtype to int
a_int =np.linspace(0, 10, 3, dtype=int)
print(a_int.dtype)


int64


In [64]:
a_int

array([ 0,  5, 10])